<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>إدارة — دليل خدماتنا</title>
<style>
body{margin:0;font-family:Tahoma,Arial;background:#f4f7fb;color:#172b40}header{background:#0876c9;color:white;padding:18px;display:flex;justify-content:space-between;align-items:center}main{max-width:1050px;margin:auto;padding:18px}.login,.panel,.stat{background:#fff;border-radius:18px;padding:18px;box-shadow:0 4px 18px #123a5a12}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat b{font-size:28px;display:block;margin-top:8px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tabs button,.actions button{border:0;border-radius:10px;padding:10px 14px;cursor:pointer}.tabs button.active,.primary{background:#0876c9;color:#fff}.row{padding:14px 0;border-bottom:1px solid #e5ebf0}.row:last-child{border:0}.muted{color:#728398}.ok{background:#18a957;color:white}.bad{background:#e33;color:white}.field{margin:12px 0}.field input,.field textarea{width:100%;padding:12px;border:1px solid #d6e1ea;border-radius:10px}.field textarea{min-height:100px}.actions{margin-top:10px;display:flex;gap:6px}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<header><b>📍 دليل خدماتنا — لوحة الإدارة</b><button onclick="location.href='index.html'">فتح التطبيق</button></header>
<main id="app"></main>
<script>
const app=document.getElementById('app');
async function api(action,opts={}){const r=await fetch('api.php?action='+action,{headers:{'Content-Type':'application/json'},...opts});const d=await r.json();if(!r.ok)throw new Error(d.error||'حدث خطأ');return d}
function login(){app.innerHTML='<div class="login"><h2>🔐 دخول الإدارة</h2><div class="field"><input id="u" placeholder="اسم المستخدم"></div><div class="field"><input id="p" type="password" placeholder="كلمة المرور"></div><button class="primary" onclick="doLogin()">دخول</button><p class="muted">غيّر بيانات الإدارة في إعدادات الخادم قبل النشر.</p></div>'}
async function doLogin(){try{await api('admin_login',{method:'POST',body:JSON.stringify({username:u.value,password:p.value})});dashboard()}catch(e){alert(e.message)}}
async function dashboard(){let s=await api('admin_stats');app.innerHTML=`<div class="stats"><div class="stat">طلبات المراجعة<b>${s.pending}</b></div><div class="stat">الخدمات المنشورة<b>${s.approved}</b></div><div class="stat">التخصصات المقترحة<b>${s.categories}</b></div><div class="stat">التقييمات<b>${s.ratings}</b></div></div><div class="tabs"><button class="active" onclick="pending()">طلبات الخدمات</button><button onclick="cats()">التخصصات</button><button onclick="news()">الأخبار والعاجل</button><button onclick="published()">الخدمات المنشورة</button><button onclick="logout()">خروج</button></div><section id="panel" class="panel"></section>`;pending()}
async function pending(){let a=await api('admin_pending');panel.innerHTML='<h2>طلبات الخدمات</h2>'+(a.length?a.map(x=>`<div class="row"><b>${x.name}</b><div class="muted">${x.type} · ${x.phone}</div><div class="actions"><button class="ok" onclick="act('admin_approve',${x.id})">قبول ونشر</button><button class="bad" onclick="act('admin_reject',${x.id})">رفض</button></div></div>`).join(''):'<p class="muted">لا توجد طلبات.</p>')}
async function cats(){let a=await api('admin_categories');panel.innerHTML='<h2>التخصصات المقترحة</h2>'+(a.length?a.map(x=>`<div class="row"><b>${x.name}</b><div class="actions"><button class="ok" onclick="act('admin_category_approve',${x.id})">اعتماد</button></div></div>`).join(''):'<p class="muted">لا توجد اقتراحات.</p>')}
async function published(){let a=await api('services');panel.innerHTML='<h2>الخدمات المنشورة</h2>'+(a.length?a.map(x=>`<div class="row"><b>${x.name}</b><div class="muted">${x.type} · ${x.phone} · ⭐ ${x.rating||0}</div><div class="actions"><button class="edit" onclick='editService(${JSON.stringify(x)})'>تعديل</button><button class="bad" onclick="act('admin_delete',${x.id})">حذف</button></div></div>`).join(''):'<p class="muted">لا توجد خدمات منشورة.</p>')}
function editService(x){panel.innerHTML=`<h2>تعديل الخدمة</h2><div class="field"><label>الاسم</label><input id="en" value="${esc(x.name)}"></div><div class="field"><label>نوع الخدمة</label><input id="et" value="${esc(x.type)}"></div><div class="field"><label>الهاتف</label><input id="ep" value="${esc(x.phone)}"></div><div class="field"><label>واتساب</label><input id="ew" value="${esc(x.whatsapp||'')}"></div><div class="field"><label>فيسبوك</label><input id="ef" value="${esc(x.facebook||'')}"></div><div class="field"><label>المنطقة</label><input id="ea" value="${esc(x.area||'')}"></div><div class="field"><label>التفاصيل</label><textarea id="ed">${esc(x.details||'')}</textarea></div><div class="actions"><button class="ok" onclick="saveEdit(${x.id})">حفظ</button><button onclick="published()">إلغاء</button></div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function saveEdit(id){await api('admin_edit',{method:'POST',body:JSON.stringify({id,name:en.value,type:et.value,phone:ep.value,whatsapp:ew.value,facebook:ef.value,area:ea.value,details:ed.value})});dashboard()}
async function news(){let n=await api('admin_news');panel.innerHTML=`<h2>الأخبار والعاجل</h2><div class="field"><textarea id="nt">${n.text}</textarea></div><button class="primary" onclick="saveNews()">حفظ الخبر</button>`}
async function saveNews(){await api('admin_news',{method:'POST',body:JSON.stringify({text:nt.value})});alert('تم الحفظ')}
async function act(a,id){await api(a,{method:'POST',body:JSON.stringify({id})});dashboard()}
async function logout(){await api('admin_logout');login()}
login();
</script></body></html>