const services=[
 {id:1,name:"محمد",type:"سيارات أجرة",rating:4.8,area:"الوادي",phone:"0550000000",wa:"0550000000",fb:"#",details:"متوفر للنقل داخل الولاية وخارجها.",img:"https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80"},
 {id:2,name:"أحمد",type:"شاحنات نقل",rating:4.6,area:"الوادي",phone:"0551111111",wa:"0551111111",fb:"#",details:"نقل البضائع والأثاث.",img:"https://images.unsplash.com/photo-1601584115197-04ecc0da31d8?auto=format&fit=crop&w=800&q=80"},
 {id:3,name:"علي",type:"شاحنات الماء",rating:4.9,area:"الرباح",phone:"0552222222",wa:"0552222222",fb:"#",details:"توصيل الماء للمنازل والمزارع.",img:"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80"},
 {id:4,name:"سعيد",type:"جرارات",rating:4.7,area:"الوادي",phone:"0553333333",wa:"0553333333",fb:"#",details:"خدمات فلاحية وحرث.",img:"https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80"},
 {id:5,name:"نور الدين",type:"جرافات",rating:4.5,area:"البيضاء",phone:"0554444444",wa:"0554444444",fb:"#",details:"أشغال وتسوية الأراضي.",img:"https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80"},
 {id:6,name:"د. أحمد",type:"طبيب عام",rating:4.9,area:"الوادي",phone:"0555555555",wa:"0555555555",fb:"#",details:"استشارات طبية عامة.",img:"https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=800&q=80"}
];
const cats=[
 ["🚚","النقل والآليات"],["🏠","العقارات"],["🩺","الصحة"],["🐄","البيطرة والفلاحة"],
 ["🔧","الحرف والخدمات"],["🚗","السيارات"],["🛍️","التجارة والمحلات"],["🎓","التعليم"],
 ["💄","الجمال والعناية"],["🎉","المناسبات"],["🏨","السياحة والإقامة"],["🐕","الحيوانات"],["➕","خدمات متنوعة"]
];
const content=document.getElementById("content"),drawer=document.getElementById("drawer"),overlay=document.getElementById("overlay");
function stars(r){return "★".repeat(Math.round(r))+"☆".repeat(5-Math.round(r))}
function serviceCard(s){return `<article class="service"><div class="rating">⭐ ${s.rating}</div><img src="${s.img}" alt="${s.type}"><div class="service-body"><h3>${s.name}</h3><div class="muted">${s.type} · ${s.area}</div><div class="actions"><a class="call" href="tel:${s.phone}">اتصال</a><a class="wa" href="https://wa.me/213${s.wa.slice(1)}" target="_blank">واتساب</a></div><button class="primary" style="margin-top:8px" onclick="showDetail(${s.id})">عرض المعلومات</button></div></article>`}
function home(){
 content.innerHTML=`<div class="searchbox"><input id="homeSearch" placeholder="ماذا تبحث عن؟"><button onclick="doSearch()">بحث</button></div>
 <div class="section-title"><h2>الخدمات</h2></div><div class="categories">${cats.map(c=>`<button class="cat" onclick="category('${c[1]}')"><span class="emoji">${c[0]}</span><b>${c[1]}</b></button>`).join("")}</div>
 <div class="section-title" style="margin-top:28px"><h2>خدمات مميزة</h2></div><div class="cards">${services.slice(0,6).map(serviceCard).join("")}</div>`;
}
function category(type){const list=type==="النقل والآليات"?services:services.filter(s=>s.type.includes(type)||type.includes(s.type)); content.innerHTML=`<div class="section-title"><h2>${type}</h2><button onclick="home()">← الرئيسية</button></div><div class="cards">${(list.length?list:services).map(serviceCard).join("")}</div>`}
function search(){content.innerHTML=`<div class="searchbox"><input id="searchInput" placeholder="اكتب اسم الخدمة أو الشخص..."><button onclick="doSearch()">بحث</button></div><div id="results"></div>`}
function doSearch(){const q=(document.querySelector("#homeSearch")||document.querySelector("#searchInput"))?.value?.trim().toLowerCase()||""; const list=services.filter(s=>(s.name+" "+s.type+" "+s.area).toLowerCase().includes(q)); const box=document.getElementById("results")||content; if(box===content) content.innerHTML=`<div class="cards">${(list.length?list:[]).map(serviceCard).join("")}</div>`; else box.innerHTML=`<div class="section-title"><h2>نتائج البحث</h2></div><div class="cards">${list.length?list.map(serviceCard).join(""):'<div class="empty">لم نجد الخدمة المطلوبة.</div>'}</div>`}
function showDetail(id){const s=services.find(x=>x.id===id);content.innerHTML=`<div class="detail"><button onclick="home()">← رجوع</button><img class="detail-img" src="${s.img}"><h1>${s.name}</h1><div class="muted">${s.type} · ${s.area}</div><div class="stars">${stars(s.rating)} <small>${s.rating}</small></div><hr><p><b>📞 الهاتف:</b> ${s.phone}</p><p><b>💬 واتساب:</b> ${s.wa}</p><p><b>🔵 فيسبوك:</b> متاح</p><h3>تفاصيل الخدمة</h3><p>${s.details}</p><div class="actions"><a class="call" href="tel:${s.phone}">📞 اتصال</a><a class="wa" href="https://wa.me/213${s.wa.slice(1)}" target="_blank">💬 واتساب</a><a class="fb" href="${s.fb}" target="_blank">🔵 فيسبوك</a></div><h3 style="margin-top:24px">⭐ قيّم هذه الخدمة</h3><div id="rate" class="stars" style="cursor:pointer">${[1,2,3,4,5].map(n=>`<span onclick="rate(${n})">☆</span>`).join("")}</div></div>`}
function rate(n){document.querySelectorAll("#rate span").forEach((e,i)=>e.textContent=i<n?"★":"☆"); toast("تم تسجيل تقييمك")}
function add(){content.innerHTML=`<div class="section-title"><h2>➕ أضف خدمتك</h2></div><form class="form" id="addForm"><div class="field"><label>الاسم *</label><input required name="name"></div><div class="field"><label>نوع الخدمة *</label><select required name="type"><option value="">اختر الخدمة</option>${cats.filter(c=>c[1]!=="خدمات متنوعة").map(c=>`<option>${c[1]}</option>`).join("")}</select></div><div class="field"><label>إذا لم تجد تخصصك</label><input name="newType" placeholder="اكتب التخصص المقترح للمراجعة"></div><div class="field"><label>رقم الهاتف *</label><input required name="phone"></div><div class="field"><label>واتساب</label><input name="wa"></div><div class="field"><label>رابط فيسبوك</label><input name="fb"></div><div class="field"><label>الصورة الشخصية / صورة الخدمة</label><input type="file" accept="image/*" name="image"></div><div class="field"><label>التفاصيل</label><textarea name="details"></textarea></div><div class="field"><label>الرابط</label><input name="link"></div><button class="primary">إرسال للمراجعة</button></form>`;document.getElementById("addForm").onsubmit=e=>{e.preventDefault();toast("تم إرسال المعلومات للمراجعة من طرف الإدارة");e.target.reset()}}
function news(){content.innerHTML=`<div class="section-title"><h2>📢 الأخبار والإعلانات</h2></div><div class="news-item"><b>🔴 عاجل</b><p>تمت إضافة خدمات جديدة إلى دليل خدماتنا.</p></div><div class="news-item"><b>📢 إعلان</b><p>يمكن لأصحاب الخدمات اقتراح تخصصات غير موجودة، وبعد مراجعتها يمكن اعتمادها.</p></div>`}
function about(){content.innerHTML=`<div class="detail"><h2>ℹ️ معلومات عنا</h2><p>دليل خدماتنا منصة محلية تجمع الخدمات وأصحاب المهن في مكان واحد، لتسهيل الوصول إليهم والتواصل معهم مباشرة.</p></div>`}
function contact(){content.innerHTML=`<div class="detail"><h2>📞 اتصل بنا</h2><p>لإضافة تعديل على معلومات خدمة منشورة أو للإبلاغ عن مشكلة، تواصل مع إدارة المنصة.</p><a class="call" style="display:block;padding:12px;border-radius:10px;text-decoration:none;color:white;text-align:center" href="tel:0550000000">اتصال بالإدارة</a></div>`}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
function page(p){({home,add,search,news,about,contact}[p]||home)();drawer.classList.remove("open");overlay.classList.remove("show");window.scrollTo(0,0)}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));
document.getElementById("menuBtn").onclick=()=>{drawer.classList.add("open");overlay.classList.add("show")};
document.getElementById("closeBtn").onclick=()=>{drawer.classList.remove("open");overlay.classList.remove("show")};
overlay.onclick=()=>{drawer.classList.remove("open");overlay.classList.remove("show")};
document.getElementById("shareBtn").onclick=async()=>{try{await navigator.share({title:"دليل خدماتنا",text:"تطبيق دليل الخدمات المحلية"}); }catch(e){toast("يمكنك مشاركة رابط التطبيق من جهازك")}};
home();
