(function(){
const groups={
'خدمات منزلية':[['كهربائي منازل','⚡'],['سباك','🚰'],['نجار','🪚'],['حداد','🔨'],['بناء وترميم','🧱'],['دهان وطلاء','🎨'],['جباس وديكور','🏠'],['ألمنيوم','🪟'],['بلاط وتركيب','◼️'],['جبس بورد','✨'],['تكييف وتبريد','❄️'],['أجهزة منزلية','🔌'],['تنظيف منازل','🧹'],['تنظيف مكاتب','🧽'],['مكافحة حشرات','🦟'],['خياطة','🧵'],['إصلاح أحذية','👞'],['نقل الأثاث','🛋️']],
'النقل والمركبات':[['سيارات أجرة','🚕'],['سيارات نقل','🚐'],['شاحنات نقل','🚚'],['شاحنات كبيرة','🚛'],['شاحنات الماء','💧'],['شاحنات الغاز','🔥'],['جرارات','🚜'],['جرافات','🏗️'],['حفارات','🚧'],['رافعات','🏗️'],['شاحنات تبريد','❄️'],['نقل البضائع','📦'],['نقل الأثاث','🛋️'],['سائق خاص','👨‍✈️'],['سفريات','🚌'],['ميكانيكي','🔧'],['كهرباء سيارات','⚡'],['تصليح سيارات','🛠️'],['تصليح شاحنات','🔩'],['غسيل سيارات','🧽'],['زيوت','🛢️'],['إطارات','🛞'],['قطع غيار','⚙️'],['بيع سيارات','🚘'],['كراء سيارات','🔑'],['دراجات نارية','🏍️'],['إصلاح دراجات','🔩']],
'العقارات':[['منازل للكراء','🏠'],['منازل للبيع','🏡'],['شقق للكراء','🏢'],['شقق للبيع','🏙️'],['محلات للكراء','🏪'],['محلات للبيع','🏬'],['مكاتب','💼'],['مستودعات','🏭'],['أراضي','🌳'],['أراضي فلاحية','🌾'],['غرف للكراء','🛏️'],['وكالات عقارية','🏢'],['تقييم عقاري','📋']],
'الصحة':[['طبيب عام','🩺'],['أطفال','👶'],['أسنان','🦷'],['عيون','👁️'],['جلدية','🧴'],['قلب','❤️'],['نساء وتوليد','🤰'],['أنف وأذن وحنجرة','👂'],['عظام ومفاصل','🦴'],['مختصون','⚕️'],['ممرضون','👨‍⚕️'],['قابلات','🤱'],['مخابر تحاليل','🧪'],['علاج طبيعي','🧘'],['صيدليات','💊'],['عيادات','🏥'],['نظارات وبصريات','👓']],
'الزراعة والحدائق':[['طبيب بيطري','🐄'],['جرارات','🚜'],['آلات فلاحية','⚙️'],['كراء آلات فلاحية','🔧'],['حرث','🌱'],['حصاد','🌾'],['حفر آبار','💧'],['أعلاف','🐑'],['بذور','🌱'],['أسمدة','🧪'],['معدات فلاحية','🧰'],['حدائق وبستنة','🌿'],['تقليم الأشجار','🌳'],['ري وسقي','💦'],['مكافحة آفات زراعية','🐛']],
'التكنولوجيا':[['هواتف','📱'],['حواسيب','💻'],['صيانة حواسيب','🛠️'],['برمجة','👨‍💻'],['تصميم مواقع','🌐'],['تطبيقات الهاتف','📲'],['شبكات وإنترنت','📡'],['كاميرات مراقبة','📷'],['صيانة إلكترونيات','🔌'],['طباعة وتصميم','🖨️'],['خدمات رقمية','💻'],['استرجاع بيانات','💾'],['صيانة هواتف','📱']],
'التعليم':[['دروس ابتدائي','📚'],['دروس متوسط','📘'],['دروس ثانوي','📖'],['تحضير بكالوريا','🎓'],['لغات','🗣️'],['رياضيات','➗'],['فيزياء','🔬'],['كيمياء','🧪'],['إعلام آلي','💻'],['دروس خصوصية','✏️'],['تحضير مسابقات','🏆'],['تعليم القرآن','📖'],['محو الأمية','📝']],
'الجمال والعناية':[['حلاقة رجالية','💈'],['تجميل نسائي','💄'],['تصفيف شعر','💇'],['مكياج','💋'],['عناية بالبشرة','✨'],['عناية بالأظافر','💅'],['حمام وعناية','🧖'],['عطور','🌸'],['حجامة','🩹'],['سبا ومساج','💆'],['مستلزمات التجميل','🧴']],
'التجارة الإلكترونية':[['تجارة إلكترونية','🌐'],['متاجر إلكترونية','🛒'],['بيع وشراء عبر الإنترنت','💻'],['إعلانات ممولة','📣'],['إدارة صفحات تجارية','📱'],['تسويق إلكتروني','📈'],['إنشاء متجر إلكتروني','🛍️'],['تصميم إعلانات','🎨'],['تصوير منتجات','📸'],['شحن التطبيقات والألعاب','🎮'],['بطاقات الألعاب','🎟️'],['بطاقات Google Play','▶️'],['بطاقات App Store','🍎'],['شحن الألعاب','🎮'],['شحن الرصيد','📲'],['دفع الفواتير إلكترونيًا','💳'],['خدمات الدفع الإلكتروني','💳'],['خدمات رقمية للتجارة','📲']],
'المحلات':[['بقالة ومواد غذائية','🛒'],['ملابس وأحذية','👕'],['أثاث ومفروشات','🛋️'],['إلكترونيات','📱'],['أجهزة كهرومنزلية','🔌'],['مواد البناء','🧱'],['قطع غيار','⚙️'],['محلات متنوعة','🏪'],['بيع بالجملة','📦'],['بيع بالتجزئة','🛍️']],
'خدمات أخرى':[['خدمات إدارية','📋'],['استخراج وثائق','📄'],['كتابة عرائض','✍️'],['ترجمة','🌐'],['محاسبة','🧾'],['خدمات تأمين','🛡️'],['استشارات','💼'],['خدمات قانونية','⚖️'],['خدمات عقود','📝'],['خدمات مالية','💰'],['خدمات مهنية','🧑‍💼'],['خدمات عامة','✨'],['تصوير ومونتاج','🎬'],['طباعة ونسخ','🖨️'],['تصميم جرافيك','🎨'],['خدمات توصيل','🛵'],['تنظيم خدمات ومواعيد','📅']]
};
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const services=()=>window.__dabbarliServices||[];
function renderGroup(category){const items=groups[category];if(!items)return false;const list=services();const html=items.map(([name,icon])=>{const count=list.filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name).length;return '<button type="button" class="category-detail-item" data-generic-specialty="'+esc(name)+'"><div class="category-detail-thumb category-detail-design" aria-hidden="true">'+icon+'</div><span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>';}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(category)+'</h2><button class="see-all" id="genericCategoryHome">‹ الرئيسية</button></div><div class="category-detail-list">'+html+'</div></div>';document.getElementById('genericCategoryHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-generic-specialty]').forEach(b=>b.addEventListener('click',()=>renderSpecialty(category,b.dataset.genericSpecialty)));return true;}
function renderSpecialty(category,name){const list=services().filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name);const html=list.length?list.map(s=>card(s)).join(''):'<div class="empty">لا توجد خدمات منشورة في هذا التخصص بعد.</div>';content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(name)+'</h2><button class="see-all" id="genericBack">‹ '+esc(category)+'</button></div><div class="services">'+html+'</div></div>';document.getElementById('genericBack')?.addEventListener('click',()=>renderGroup(category));}
window.renderCategoryDetails=renderGroup;window.renderCategorySpecialty=renderSpecialty;
function wrap(){if(typeof window.category!=='function'){setTimeout(wrap,100);return}if(window.category.__genericDetailsWrapped)return;const original=window.category;const wrapped=function(type){const t=String(type||'').trim();if(groups[t]){window.__dabbarliServices=services();renderGroup(t);return}return original.apply(this,arguments)};wrapped.__genericDetailsWrapped=true;window.category=wrapped;}
function splitHomeCategories(){document.querySelectorAll('.categories').forEach(box=>{const old=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='التجارة والمحلات');if(old)old.remove();const oldEdu=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='الدروس والتعليم');if(oldEdu)oldEdu.textContent='التعليم';if(!box.querySelector('[data-dabberli-split="التجارة الإلكترونية"]')){const anchor=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='خدمات أخرى');['التجارة الإلكترونية','المحلات'].forEach(name=>{const b=document.createElement('button');b.className='cat';b.setAttribute('data-dabberli-split',name);b.innerHTML='<b>'+name+'</b>';b.onclick=()=>category(name);anchor?box.insertBefore(b,anchor):box.appendChild(b);});}})}
function ensureNewsTicker(){const hero=document.querySelector('.hero');if(!hero||document.getElementById('dabbarliNewsTicker'))return;const ticker=document.createElement('section');ticker.id='dabbarliNewsTicker';ticker.setAttribute('dir','rtl');ticker.innerHTML='<div class="dab-news-label">📰 الأخبار</div><div class="dab-news-track"><div class="dab-news-text">جاري تحميل آخر الأخبار...</div></div>';hero.insertAdjacentElement('afterend',ticker);const style=document.createElement('style');style.textContent='#dabbarliNewsTicker{margin:14px 14px 0;min-height:48px;background:#fff;border:1px solid #e7ede9;border-radius:18px;box-shadow:0 8px 20px -10px rgba(8,50,33,.22);display:flex;align-items:center;overflow:hidden;color:#122019}#dabbarliNewsTicker .dab-news-label{flex:none;background:#0b8a56;color:#fff;font-weight:800;padding:12px 18px;font-size:14px}#dabbarliNewsTicker .dab-news-track{flex:1;overflow:hidden;white-space:nowrap;padding:0 14px}#dabbarliNewsTicker .dab-news-text{display:inline-block;font-size:14px;font-weight:600;color:#344139;animation:dabberliTicker 18s linear infinite}@keyframes dabberliTicker{from{transform:translateX(-100%)}to{transform:translateX(100%)}}@media(max-width:700px){#dabbarliNewsTicker{margin:10px 12px 0;min-height:44px;border-radius:14px}#dabbarliNewsTicker .dab-news-label{padding:10px 12px;font-size:12px}#dabbarliNewsTicker .dab-news-track{padding:0 10px}#dabbarliNewsTicker .dab-news-text{font-size:12px}}';document.head.appendChild(style);loadNewsTicker(ticker.querySelector('.dab-news-text'));}
async function loadNewsTicker(target){try{if(!window.supabase||!window.SUPABASE_URL||!window.SUPABASE_ANON_KEY){target.textContent='تابع آخر الأخبار والمستجدات على دبّرلي';return}const c=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);const {data,error}=await c.from('news').select('*').order('created_at',{ascending:false}).limit(8);if(error||!data||!data.length){target.textContent='تابع آخر الأخبار والمستجدات على دبّرلي';return}const text=data.map(n=>String(n.title||n.text||n.content||'')).filter(Boolean).join('   •   ');target.textContent=text||'تابع آخر الأخبار والمستجدات على دبّرلي';}catch(e){target.textContent='تابع آخر الأخبار والمستجدات على دبّرلي'}}
function boot(){splitHomeCategories();ensureNewsTicker();wrap();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,800);setTimeout(boot,2000);
})();
