(function(){
const groups={
'خدمات منزلية':[['كهربائي منازل','⚡'],['سباك','🚰'],['نجار','🪚'],['حداد','🔨'],['بناء وترميم','🧱'],['دهان وطلاء','🎨'],['جباس وديكور','🏠'],['ألمنيوم','🪟'],['بلاط وتركيب','◼️'],['جبس بورد','✨'],['تكييف وتبريد','❄️'],['أجهزة منزلية','🔌'],['تنظيف منازل','🧹'],['تنظيف مكاتب','🧽'],['مكافحة حشرات','🦟'],['خياطة','🧵'],['إصلاح أحذية','👞'],['نقل الأثاث','🛋️']],
'النقل والمركبات':[['سيارات أجرة','🚕'],['سيارات نقل','🚐'],['شاحنات نقل','🚚'],['شاحنات كبيرة','🚛'],['شاحنات الماء','💧'],['شاحنات الغاز','🔥'],['جرارات','🚜'],['جرافات','🏗️'],['حفارات','🚧'],['رافعات','🏗️'],['شاحنات تبريد','❄️'],['نقل البضائع','📦'],['نقل الأثاث','🛋️'],['سائق خاص','👨‍✈️'],['سفريات','🚌'],['ميكانيكي','🔧'],['كهرباء سيارات','⚡'],['تصليح سيارات','🛠️'],['تصليح شاحنات','🔩'],['غسيل سيارات','🧽'],['زيوت','🛢️'],['إطارات','🛞'],['قطع غيار','⚙️'],['بيع سيارات','🚘'],['كراء سيارات','🔑'],['دراجات نارية','🏍️'],['إصلاح دراجات','🔩']],
'العقارات':[['منازل للكراء','🏠'],['منازل للبيع','🏡'],['شقق للكراء','🏢'],['شقق للبيع','🏙️'],['محلات للكراء','🏪'],['محلات للبيع','🏬'],['مكاتب','💼'],['مستودعات','🏭'],['أراضي','🌳'],['أراضي فلاحية','🌾'],['غرف للكراء','🛏️'],['وكالات عقارية','🏢'],['تقييم عقاري','📋']],
'الصحة':[['طبيب عام','🩺'],['أطفال','👶'],['أسنان','🦷'],['عيون','👁️'],['جلدية','🧴'],['قلب','❤️'],['نساء وتوليد','🤰'],['أنف وأذن وحنجرة','👂'],['عظام ومفاصل','🦴'],['مختصون','⚕️'],['ممرضون','👨‍⚕️'],['قابلات','🤱'],['مخابر تحاليل','🧪'],['علاج طبيعي','🧘'],['صيدليات','💊'],['عيادات','🏥'],['نظارات وبصريات','👓']],
'الزراعة والحدائق':[['طبيب بيطري','🐄'],['جرارات','🚜'],['آلات فلاحية','⚙️'],['كراء آلات فلاحية','🔧'],['حرث','🌱'],['حصاد','🌾'],['حفر آبار','💧'],['أعلاف','🐑'],['بذور','🌱'],['أسمدة','🧪'],['معدات فلاحية','🧰'],['حدائق وبستنة','🌿'],['تقليم الأشجار','🌳'],['ري وسقي','💦'],['مكافحة آفات زراعية','🐛']],
'التكنولوجيا':[['هواتف','📱'],['حواسيب','💻'],['صيانة حواسيب','🛠️'],['برمجة','👨‍💻'],['تصميم مواقع','🌐'],['تطبيقات الهاتف','📲'],['شبكات وإنترنت','📡'],['كاميرات مراقبة','📷'],['صيانة إلكترونيات','🔌'],['طباعة وتصميم','🖨️'],['خدمات رقمية','💻'],['استرجاع بيانات','💾'],['صيانة هواتف','📱']],
'التعليم':[['دروس ابتدائي','📚'],['دروس متوسط','📘'],['دروس ثانوي','📖'],['تحضير بكالوريا','🎓'],['لغات','🗣️'],['رياضيات','➗'],['فيزياء','🔬'],['كيمياء','🧪'],['إعلام آلي','💻'],['دروس خصوصية','✏️'],['تحضير مسابقات','🏆'],['تعليم القرآن','📖'],['محو الأمية','📝']],
'الجمال والعناية':[['حلاقة رجالية','💈'],['تجميل نسائي','💄'],['تصفيف شعر','💇'],['مكياج','💋'],['عناية بالبشرة','✨'],['عناية بالأظافر','💅'],['حمام وعناية','🧖'],['عطور','🌸'],['حجامة','🩹'],['سبا ومساج','💆'],['مستلزمات التجميل','🧴']],
'التجارة الإلكترونية':[['تجارة إلكترونية','🌐'],['متاجر إلكترونية','🛒'],['بيع وشراء عبر الإنترنت','💻'],['إعلانات ممولة','📣'],['إدارة صفحات تجارية','📱'],['تسويق إلكتروني','📈'],['إنشاء متجر إلكتروني','🛍️'],['تصميم إعلانات','🎨'],['تصوير منتجات','📸'],['شحن التطبيقات والألعاب','🎮'],['بطاقات الألعاب','🎟️'],['بطاقات Google Play','▶️'],['بطاقات App Store','🍎'],['شحن الألعاب','🎮'],['شحن الرصيد','📲'],['دفع الفواتير إلكترونيًا','💳'],['خدمات الدفع الإلكتروني','💳'],['خدمات رقمية للتجارة','📲']],
'المحلات':[['بقالة ومواد غذائية','🛒'],['ملابس وأحذية','👕'],['أثاث ومفروشات','🛋️'],['إلكترونيات','📱'],['أجهزة كهرومنزلية','🔌'],['مواد البناء','🧱'],['قطع غيار','⚙️'],['محلات متنوعة','🏪'],['بيع بالجملة','📦'],['بيع بالتجزئة','🛍️']],
'خدمات أخرى':[['خدمات إدارية','📋'],['استخراج وثائق','📄'],['كتابة عرائض','✍️'],['ترجمة','🌐'],['محاسبة','🧾'],['خدمات تأمين','🛡️'],['استشارات','💼'],['خدمات قانونية','⚖️'],['خدمات عقود','📝'],['خدمات مالية','💰'],['خدمات مهنية','🧑‍💼'],['خدمات عامة','✨'],['تصوير ومونتاج','🎬'],['طباعة ونسخ','🖨️'],['تصميم جرافيك','🎨'],['خدمات توصيل','🛵'],['تنظيم خدمات ومواعيد','📅']]
};
const publicServices=[
{id:'public-yassir',name:'Yassir',category:'النقل والمركبات',specialty:'سيارات أجرة',area:'الجزائر',phone:'',whatsapp:'',facebook:'',link:'https://www.yassir.io',details:'خدمات تنقل وتوصيل وطعام وبقالة عبر منصة يسير.',rating:0,img:''},
{id:'public-yalidine',name:'Yalidine',category:'خدمات أخرى',specialty:'خدمات توصيل',area:'الجزائر',link:'https://www.yalidine.com',details:'توصيل الطرود والتجارة الإلكترونية والدفع عند الاستلام.',rating:0,img:''},
{id:'public-zr',name:'ZR Express',category:'خدمات أخرى',specialty:'خدمات توصيل',area:'الجزائر',phone:'023000000',link:'https://www.zrexpress.net',details:'توصيل سريع، Stop Desk، الدفع عند التسليم وخدمات التجارة الإلكترونية.',rating:0,img:''},
{id:'public-numilog',name:'Numilog',category:'النقل والمركبات',specialty:'نقل البضائع',area:'الجزائر',phone:'0770963463',link:'https://numilog.dz',details:'نقل ولوجستيك وحلول متكاملة لسلاسل الإمداد.',rating:0,img:''},
{id:'public-safar',name:'Safar El Amir',category:'النقل والمركبات',specialty:'كراء سيارات',area:'الجزائر',link:'https://www.safarelamir.com',details:'كراء سيارات وخدمات مع سائق وتحويلات بين المطارات والفنادق والمدن.',rating:0,img:''},
{id:'public-airalgerie',name:'Air Algérie',category:'النقل والمركبات',specialty:'سفريات',area:'الجزائر',phone:'021986363',link:'https://airalgerie.dz/ar/',details:'رحلات جوية وطنية ودولية وحجز التذاكر.',rating:0,img:''},
{id:'public-tassili',name:'Tassili Airlines',category:'النقل والمركبات',specialty:'سفريات',area:'الجزائر',phone:'023824353',link:'https://www.tassiliairlines.dz',details:'رحلات جوية وحجز إلكتروني.',rating:0,img:''},
{id:'public-sntf',name:'SNTF',category:'النقل والمركبات',specialty:'سفريات',area:'الجزائر',phone:'021711510',link:'https://www.sntf.dz',details:'نقل المسافرين والبضائع بالسكك الحديدية.',rating:0,img:''},
{id:'public-aramex',name:'Aramex Algérie',category:'خدمات أخرى',specialty:'خدمات توصيل',area:'الجزائر',phone:'0982312412',link:'https://www.aramex.com/dz/en',details:'شحن سريع واستلام وتسليم ووكالات في عدة ولايات.',rating:0,img:''},
{id:'public-maystro',name:'Maystro Delivery',category:'خدمات أخرى',specialty:'خدمات توصيل',area:'الجزائر',link:'https://maystro-delivery.com',details:'توصيل سريع، تخزين، استلام، تغليف وتحصيل نقدي.',rating:0,img:''},
{id:'public-ooredoo',name:'Ooredoo Algérie',category:'التكنولوجيا',specialty:'شبكات وإنترنت',area:'الجزائر',link:'https://www.ooredoo.dz/ar/',details:'اتصالات الهاتف النقال والإنترنت والخدمات الرقمية.',rating:0,img:''},
{id:'public-djezzy',name:'Djezzy',category:'التكنولوجيا',specialty:'شبكات وإنترنت',area:'الجزائر',link:'https://www.djezzy.dz/',details:'هاتف نقال، إنترنت وخدمات رقمية.',rating:0,img:''},
{id:'public-mobilis',name:'Mobilis',category:'التكنولوجيا',specialty:'شبكات وإنترنت',area:'الجزائر',phone:'0655002999',link:'https://mobilis.dz',details:'هاتف نقال، إنترنت وخدمات رقمية.',rating:0,img:''},
{id:'public-at',name:'Algérie Télécom',category:'التكنولوجيا',specialty:'شبكات وإنترنت',area:'الجزائر',phone:'12',link:'https://www.algerietelecom.dz',details:'هاتف ثابت وإنترنت وخدمات الألياف والاتصالات.',rating:0,img:''},
{id:'public-iris',name:'IRIS Algérie',category:'المحلات',specialty:'إلكترونيات',area:'سطيف / الجزائر',phone:'036448559',link:'https://iris.dz/ar',details:'إلكترونيات وأجهزة كهرومنزلية وهواتف.',rating:0,img:''},
{id:'public-condor',name:'Condor Algérie',category:'المحلات',specialty:'أجهزة كهرومنزلية',area:'برج بوعريريج / الجزائر',phone:'035876319',link:'https://condor.dz',details:'أجهزة كهرومنزلية وإلكترونيات وحلول تكييف.',rating:0,img:''},
{id:'public-naftal',name:'Naftal',category:'النقل والمركبات',specialty:'زيوت',area:'الجزائر',phone:'3305',link:'https://www.naftal.dz',details:'توزيع الوقود ومواد الطاقة وخدمات مرتبطة بالنقل.',rating:0,img:''},
{id:'public-gaco',name:'GACO, Sarl',category:'خدمات منزلية',specialty:'تكييف وتبريد',area:'قسنطينة',link:'https://dz.kompass.com/x/service/',details:'معدات وتركيبات التبريد والتكييف والتدفئة.',rating:0,img:''},
{id:'public-liftal',name:'LIFTAL, Sarl',category:'خدمات أخرى',specialty:'خدمات مهنية',area:'ورقلة',link:'https://dz.kompass.com/x/service/',details:'خدمات ومعدات الرفع والمناولة.',rating:0,img:''},
{id:'public-hbtech',name:'HB Technologies,Spa',category:'التكنولوجيا',specialty:'خدمات رقمية',area:'الجزائر',link:'https://dz.kompass.com/x/service/',details:'حلول وخدمات تكنولوجية.',rating:0,img:''},
{id:'public-normiso',name:'NORMISO,Sarl',category:'خدمات أخرى',specialty:'بناء وترميم',area:'الشراقة، الجزائر',link:'https://dz.kompass.com/x/service/',details:'هندسة وأشغال مدنية وخدمات إنجاز.',rating:0,img:''},
{id:'public-futuremotors',name:'FUTURE MOTORS ALGERIE,Sarl',category:'النقل والمركبات',specialty:'جرافات',area:'وادي السمار، الجزائر',link:'https://dz.kompass.com/x/service/',details:'معدات وآليات للأشغال والحفر.',rating:0,img:''},
{id:'public-saheltaxi',name:'SAHEL TAXI',category:'النقل والمركبات',specialty:'سيارات نقل',area:'بومرداس',link:'https://www.pagesmaghreb.com/entreprises/transports-et-services-connexes/automobiles-transports/algerie',details:'نقل الأشخاص وتأجير مركبات للشركات ونقل العمال.',rating:0,img:''}
];
const transport=groups['النقل والمركبات'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const services=()=>window.__dabbarliServices||[];
function renderGroup(category){const items=groups[category];if(!items)return false;const data=services();const html=items.map(([name,icon])=>{const count=data.filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name).length;return '<button type="button" class="category-detail-item" data-generic-specialty="'+esc(name)+'"><div class="category-detail-thumb category-detail-design">'+icon+'</div><span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>'}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(category)+'</h2><button class="see-all" id="genericCategoryHome">‹ الرئيسية</button></div><div class="category-detail-list">'+html+'</div></div>';document.getElementById('genericCategoryHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-generic-specialty]').forEach(b=>b.addEventListener('click',()=>renderSpecialty(category,b.dataset.genericSpecialty)));return true}
function renderSpecialty(category,name){const data=services().filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name);content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(name)+'</h2><button class="see-all" id="genericBack">‹ '+esc(category)+'</button></div><div class="services">'+(data.length?data.map(s=>card(s)).join(''):'<div class="empty">لا توجد خدمات منشورة في هذا التخصص بعد.</div>')+'</div></div>';document.getElementById('genericBack')?.addEventListener('click',()=>renderGroup(category))}
function renderTransportDetails(){const data=services();const html=transport.map(([name,icon])=>{const count=data.filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name).length;return '<button type="button" class="category-detail-item" data-transport="'+esc(name)+'"><div class="category-detail-thumb category-detail-design">'+icon+'</div><span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>'}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>النقل والمركبات</h2><button class="see-all" id="transportHome">‹ الرئيسية</button></div><div class="category-detail-list">'+html+'</div></div>';document.getElementById('transportHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-transport]').forEach(b=>b.addEventListener('click',()=>renderSpecialty('النقل والمركبات',b.dataset.transport)))}
window.renderCategoryDetails=renderGroup;window.renderCategorySpecialty=renderSpecialty;window.renderTransportDetails=renderTransportDetails;
function addRelatedStyles(){if(document.getElementById('relatedProvidersStyle'))return;const s=document.createElement('style');s.id='relatedProvidersStyle';s.textContent='.related-providers{margin-top:28px;padding:16px 0 4px;border-top:1px solid #e8eee9}.related-providers .related-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.related-providers h3{margin:0;font-size:20px;font-weight:800}.related-providers .related-sub{margin:5px 0 0;color:#7b8580;font-size:13px}.related-providers .related-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;overflow-x:auto;padding-bottom:6px}.related-providers .related-more{border:0;background:#eaf7f0;color:#087c50;border-radius:20px;padding:10px 15px;font-weight:800;white-space:nowrap;cursor:pointer}.related-providers .service-img{height:120px}@media(max-width:700px){.related-providers h3{font-size:17px}.related-providers .related-grid{grid-template-columns:repeat(3,190px);gap:10px}.related-providers .service-img{height:105px}.related-providers .related-more{font-size:11px;padding:8px 10px}}';document.head.appendChild(s)}
function relatedProviders(id){const current=services().find(x=>String(x.id)===String(id));const detail=content.querySelector('.detail');if(!current||!detail)return;const key=String(current.specialty||current.name||'').trim();let others=services().filter(x=>String(x.id)!==String(id)&&(String(x.specialty||'').trim()===key||String(x.name||'').trim()===key));if(!others.length)others=services().filter(x=>String(x.id)!==String(id)&&String(x.category||'')===String(current.category||''));others=others.slice().sort((a,b)=>Number(b.rating||0)-Number(a.rating||0));addRelatedStyles();const box=document.createElement('section');box.className='related-providers';box.innerHTML='<div class="related-head"><div><h3>👥 مزودون آخرون لنفس الخدمة</h3><p class="related-sub">اكتشف مزودين آخرين يقدمون نفس الخدمة</p></div><button class="related-more" type="button">‹ عرض الكل</button></div><div class="related-grid"></div>';const grid=box.querySelector('.related-grid');grid.innerHTML=others.length?others.slice(0,6).map(card).join(''):'<div class="related-empty">لا يوجد مزودون آخرون لنفس الخدمة حاليًا.</div>';box.querySelector('.related-more').onclick=()=>{grid.innerHTML=others.length?others.map(card).join(''):'<div class="related-empty">لا يوجد مزودون آخرون لنفس الخدمة حاليًا.</div>';box.querySelector('.related-more').remove()};detail.parentElement.appendChild(box)}
function splitHome(){document.querySelectorAll('.categories').forEach(box=>{const old=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='التجارة والمحلات');if(old)old.remove();const edu=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='الدروس والتعليم');if(edu)edu.textContent='التعليم';if(!box.querySelector('[data-dabberli-split="التجارة الإلكترونية"]')){const anchor=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='خدمات أخرى');['التجارة الإلكترونية','المحلات'].forEach(name=>{const b=document.createElement('button');b.className='cat';b.setAttribute('data-dabberli-split',name);b.innerHTML='<b>'+name+'</b>';b.onclick=()=>category(name);anchor?box.insertBefore(b,anchor):box.appendChild(b)})}})}
function wrap(){if(typeof window.loadServices!=='function'||typeof window.home!=='function'){setTimeout(wrap,100);return}if(window.loadServices.__publicSeed)return;const original=window.loadServices;const seeded=async function(){await original();const base=(Array.isArray(window.__dabbarliServices)?window.__dabbarliServices:[]).filter(x=>String(x.id)!=='demo-1');const ids=new Set(base.map(x=>String(x.id)));publicServices.forEach(x=>{if(!ids.has(String(x.id)))base.push({...x,status:'approved',source:'public-directory'})});window.__dabbarliServices=base;services.length=0;services.push(...base)};seeded.__publicSeed=true;window.loadServices=seeded;const oldCard=window.card;if(typeof oldCard==='function'&&!oldCard.__publicCard){const c=function(s){const html=oldCard(s);if(Number(s.rating||0)>0)return html;return html.replace(/<div class="rating-row">.*?<\/div>/,'<div class="rating-row"><span class="muted">جديد</span></div>')};c.__publicCard=true;window.card=c}const oldDetail=window.showDetail;if(typeof oldDetail==='function'&&!oldDetail.__relatedWrapped){const d=function(id){oldDetail(id);setTimeout(()=>relatedProviders(id),80);setTimeout(()=>relatedProviders(id),300)};window.showDetail=d;d.__relatedWrapped=true}const oldCategory=window.category;if(typeof oldCategory==='function'&&!oldCategory.__genericWrapped){const cat=function(type){const t=String(type||'').trim();if(t==='النقل والمركبات'||t==='النقل والآليات'){renderTransportDetails();return}if(groups[t]){renderGroup(t);return}return oldCategory.apply(this,arguments)};window.category=cat;cat.__genericWrapped=true}setTimeout(splitHome,300);new MutationObserver(()=>setTimeout(splitHome,40)).observe(document.getElementById('content')||document.body,{childList:true,subtree:true})}
wrap();
})();