(function(){
const groups={
'خدمات منزلية':[['كهربائي منازل','⚡'],['سباك','🚰'],['نجار','🪚'],['حداد','🔨'],['بناء وترميم','🧱'],['دهان وطلاء','🎨'],['جباس وديكور','🏠'],['ألمنيوم','🪟'],['بلاط وتركيب','◼️'],['جبس بورد','✨'],['تكييف وتبريد','❄️'],['أجهزة منزلية','🔌'],['تنظيف منازل','🧹'],['تنظيف مكاتب','🧽'],['مكافحة حشرات','🦟'],['خياطة','🧵'],['إصلاح أحذية','👞'],['نقل الأثاث','🛋️']],
'النقل والمركبات':[['سيارات أجرة','🚕'],['سيارات نقل','🚐'],['شاحنات نقل','🚚'],['شاحنات كبيرة','🚛'],['شاحنات الماء','💧'],['شاحنات الغاز','🔥'],['جرارات','🚜'],['جرافات','🏗️'],['حفارات','🚧'],['رافعات','🏗️'],['شاحنات تبريد','❄️'],['نقل البضائع','📦'],['نقل الأثاث','🛋️'],['سائق خاص','👨‍✈️'],['سفريات','🚌'],['ميكانيكي','🔧'],['كهرباء سيارات','⚡'],['تصليح سيارات','🛠️'],['تصليح شاحنات','🔩'],['غسيل سيارات','🧽'],['زيوت','🛢️'],['إطارات','🛞'],['قطع غيار','⚙️'],['بيع سيارات','🚘'],['كراء سيارات','🔑'],['دراجات نارية','🏍️'],['إصلاح دراجات','🔩']],
'العقارات':[['منازل للكراء','🏠'],['منازل للبيع','🏡'],['شقق للكراء','🏢'],['شقق للبيع','🏙️'],['محلات للكراء','🏪'],['محلات للبيع','🏬'],['مكاتب','💼'],['مستودعات','🏭'],['أراضي','🌳'],['أراضي فلاحية','🌾'],['غرف للكراء','🛏️'],['وكالات عقارية','🏢'],['تقييم عقاري','📋']],
'الصحة':[['طبيب عام','🩺'],['أطفال','👶'],['أسنان','🦷'],['عيون','👁️'],['جلدية','🧴'],['قلب','❤️'],['نساء وتوليد','🤰'],['أنف وأذن وحنجرة','👂'],['عظام ومفاصل','🦴'],['مختصون','⚕️'],['ممرضون','👨‍⚕️'],['قابلات','🤱'],['مخابر تحاليل','🧪'],['علاج طبيعي','🧘'],['صيدليات','💊'],['عيادات','🏥'],['نظارات وبصريات','👓']],
'الزراعة والحدائق':[['طبيب بيطري','🐄'],['جرارات','🚜'],['آلات فلاحية','⚙️'],['كراء آلات فلاحية','🔧'],['حرث','🌱'],['حصاد','🌾'],['حفر آبار','💧'],['أعلاف','🐑'],['بذور','🌱'],['أسمدة','🧪'],['معدات فلاحية','🧰'],['حدائق وبستنة','🌿'],['تقليم الأشجار','🌳'],['ري وسقي','💦'],['مكافحة آفات زراعية','🐛']],
'التكنولوجيا':[['هواتف','📱'],['حواسيب','💻'],['صيانة حواسيب','🛠️'],['برمجة','👨‍💻'],['تصميم مواقع','🌐'],['تطبيقات الهاتف','📲'],['شبكات وإنترنت','📡'],['كاميرات مراقبة','📷'],['صيانة إلكترونيات','🔌'],['طباعة وتصميم','🖨️'],['خدمات رقمية','💻'],['استرجاع بيانات','💾'],['صيانة هواتف','📱']],
'التعليم':[['دروس ابتدائي','📚'],['دروس متوسط','📘'],['دروس ثانوي','📖'],['تحضير بكالوريا','🎓'],['لغات','🗣️'],['رياضيات','➗'],['فيزياء','🔬'],['كيمياء','🧪'],['إعلام آلي','💻'],['دروس خصوصية','✏️'],['تحضير مسابقات','🏆'],['تعليم القرآن','📖'],['محو الأمية','📝']],
'الجمال والعناية':[['حلاقة رجالية','💈'],['تجميل نسائي','💄'],['تصفيف شعر','💇'],['مكياج','💋'],['عناية بالبشرة','✨'],['عناية بالأظافر','💅'],['حمام وعناية','🧖'],['عطور','🌸'],['حجامة','🩹'],['سبا ومساج','💆'],['مستلزمات التجميل','🧴']],
'التجارة الإلكترونية':[['تجارة إلكترونية','🌐'],['متاجر إلكترونية','🛒'],['بيع وشراء عبر الإنترنت','💻'],['إعلانات ممولة','📣'],['إدارة صفحات تجارية','📱'],['تسويق إلكتروني','📈'],['إنشاء متجر إلكتروني','🛍️'],['تصميم إعلانات','🎨'],['تصوير منتجات','📸'],['شحن التطبيقات والألعاب','🎮'],['بطاقات الألعاب','🎟️'],['بطاقات Google Play','▶️'],['بطاقات App Store','🍎'],['شحن الألعاب','🎮'],['شحن الرصيد','📲'],['دفع الفواتير إلكترونيًا','💳'],['خدمات الدفع الإلكتروني','💳'],['خدمات رقمية للتجارة','📲']],
'المحلات':[['بقالة ومواد غذائية','🛒'],['ملابس وأحذية','👕'],['أثاث ومفروشات','🛋️'],['إلكترونيات','📱'],['أجهزة كهرومنزلية','🔌'],['مواد البناء','🧱'],['قطع غيار','⚙️'],['محلات متنوعة','🏪'],['بيع بالجملة','📦'],['بيع بالتجزئة','🛍️']],
'خدمات أخرى':[['خدمات إدارية','📋'],['استخراج وثائق','📄'],['كتابة عرائض','✍️'],['ترجمة','🌐'],['محاسبة','🧾'],['خدمات تأمين','🛡️'],['استشارات','💼'],['خدمات قانونية','⚖️'],['خدمات عقود','📝'],['خدمات مالية','💰'],['خدمات مهنية','🧑‍💼'],['خدمات عامة','✨'],['تصوير ومونتاج','🎬'],['طباعة ونسخ','🖨️'],['تصميم جرافيك','🎨'],['خدمات توصيل','🛵'],['تنظيم خدمات ومواعيد','📅']]
};
const transport=groups['النقل والمركبات'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const services=()=>window.__dabbarliServices||[];
function renderGroup(category){const items=groups[category];if(!items)return false;const data=services();const html=items.map(([name,icon])=>{const count=data.filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name).length;return '<button type="button" class="category-detail-item" data-generic-specialty="'+esc(name)+'"><div class="category-detail-thumb category-detail-design">'+icon+'</div><span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>'}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(category)+'</h2><button class="see-all" id="genericCategoryHome">‹ الرئيسية</button></div><div class="category-detail-list">'+html+'</div></div>';document.getElementById('genericCategoryHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-generic-specialty]').forEach(b=>b.addEventListener('click',()=>renderSpecialty(category,b.dataset.genericSpecialty)));return true}
function renderSpecialty(category,name){const data=services().filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name);content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(name)+'</h2><button class="see-all" id="genericBack">‹ '+esc(category)+'</button></div><div class="services">'+(data.length?data.map(s=>card(s)).join(''):'<div class="empty">لا توجد خدمات منشورة في هذا التخصص بعد.</div>')+'</div></div>';document.getElementById('genericBack')?.addEventListener('click',()=>renderGroup(category))}
function renderTransportDetails(){const data=services();const html=transport.map(([name,icon])=>{const count=data.filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name).length;return '<button type="button" class="category-detail-item" data-transport="'+esc(name)+'"><div class="category-detail-thumb category-detail-design">'+icon+'</div><span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>'}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>النقل والمركبات</h2><button class="see-all" id="transportHome">‹ الرئيسية</button></div><div class="category-detail-list">'+html+'</div></div>';document.getElementById('transportHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-transport]').forEach(b=>b.addEventListener('click',()=>renderSpecialty('النقل والمركبات',b.dataset.transport)))}
window.renderCategoryDetails=renderGroup;window.renderCategorySpecialty=renderSpecialty;window.renderTransportDetails=renderTransportDetails;
function splitHomeCategories(){document.querySelectorAll('.categories').forEach(box=>{const old=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='التجارة والمحلات');if(old)old.remove();const edu=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='الدروس والتعليم');if(edu)edu.textContent='التعليم';if(!box.querySelector('[data-dabberli-split="التجارة الإلكترونية"]')){const anchor=[...box.querySelectorAll('.cat')].find(b=>b.textContent.trim()==='خدمات أخرى');['التجارة الإلكترونية','المحلات'].forEach(name=>{const b=document.createElement('button');b.className='cat';b.setAttribute('data-dabberli-split',name);b.innerHTML='<b>'+name+'</b>';b.onclick=()=>category(name);anchor?box.insertBefore(b,anchor):box.appendChild(b)})}})}
function addRelatedStyles(){if(document.getElementById('relatedProvidersStyle'))return;const s=document.createElement('style');s.id='relatedProvidersStyle';s.textContent='.related-providers{margin-top:28px;padding:16px 0 4px;border-top:1px solid #e8eee9}.related-providers .related-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.related-providers h3{margin:0;font-size:20px;font-weight:800}.related-providers .related-sub{margin:5px 0 0;color:#7b8580;font-size:13px}.related-providers .related-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;overflow-x:auto;padding-bottom:6px}.related-providers .related-grid .service{min-width:0}.related-providers .related-more{border:0;background:#eaf7f0;color:#087c50;border-radius:20px;padding:10px 15px;font-weight:800;white-space:nowrap;cursor:pointer}.related-providers .service-img{height:120px}.related-providers .service-body h3{font-size:14px}.related-providers .primary{font-size:12px}.related-providers .related-empty{padding:16px;background:#f7faf8;border-radius:14px;color:#68736d}@media(max-width:700px){.related-providers{margin-top:24px;padding-top:14px}.related-providers .related-head{align-items:flex-start}.related-providers h3{font-size:17px}.related-providers .related-sub{font-size:11px}.related-providers .related-grid{grid-template-columns:repeat(3,190px);gap:10px}.related-providers .service-img{height:105px}.related-providers .service-body h3{font-size:13px}.related-providers .related-more{font-size:11px;padding:8px 10px}}';document.head.appendChild(s)}
function relatedProviders(id){const current=services().find(x=>String(x.id)===String(id));const detail=content.querySelector('.detail');if(!current||!detail)return;const old=content.querySelector('.related-providers');if(old)old.remove();const key=String(current.specialty||current.name||'').trim();let others=services().filter(x=>String(x.id)!==String(current.id)&&key&&String(x.specialty||x.name||'').trim()===key);if(!others.length&&current.category)others=services().filter(x=>String(x.id)!==String(current.id)&&String(x.category||'').trim()===String(current.category).trim());others=others.slice().sort((a,b)=>Number(b.rating||0)-Number(a.rating||0)).slice(0,6);const section=document.createElement('section');section.className='related-providers';section.innerHTML='<div class="related-head"><div><h3>👥 مزودون آخرون لنفس الخدمة</h3><p class="related-sub">اكتشف مزودين آخرين يقدمون نفس الخدمة</p></div><button type="button" class="related-more">‹ عرض الكل</button></div><div class="related-grid"></div>';const grid=section.querySelector('.related-grid');if(others.length){grid.innerHTML=others.map(s=>card(s)).join('');section.querySelector('.related-more').onclick=()=>{grid.style.gridTemplateColumns='repeat(1,minmax(0,1fr))';grid.innerHTML=others.map(s=>card(s)).join('');section.querySelector('.related-more').style.display='none';section.scrollIntoView({behavior:'smooth',block:'start'})}}else{grid.innerHTML='<div class="related-empty">لا يوجد مزودون آخرون لنفس الخدمة حاليًا.</div>';section.querySelector('.related-more').style.display='none'}detail.insertAdjacentElement('afterend',section)}
function wrapDetail(){if(typeof window.showDetail!=='function'){setTimeout(wrapDetail,100);return}if(window.showDetail.__relatedWrapped)return;const original=window.showDetail;const wrapped=function(id){window.__dabbarliCurrentServiceId=id;original.apply(this,arguments);setTimeout(()=>relatedProviders(id),80);setTimeout(()=>relatedProviders(id),350)};wrapped.__relatedWrapped=true;window.showDetail=wrapped}
function wrapCategory(){if(typeof window.category!=='function'){setTimeout(wrapCategory,100);return}if(window.category.__genericDetailsWrapped)return;const original=window.category;const wrapped=function(type){const t=String(type||'').trim();if(t==='النقل والمركبات'||t==='النقل والآليات'){renderTransportDetails();return}if(groups[t]){window.__dabbarliServices=services();renderGroup(t);return}return original.apply(this,arguments)};wrapped.__genericDetailsWrapped=true;window.category=wrapped}
function boot(){addRelatedStyles();splitHomeCategories();wrapCategory();wrapDetail()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,300);setTimeout(boot,1000);setTimeout(boot,2000);
})();