// Supabase connection for دبّرلي
window.SUPABASE_URL = "https://rrybfflettigvfgpfby1.supabase.co";
window.SUPABASE_ANON_KEY = "sb_publishable_JFoAUuoK0X-eGsQ8xNNnCA_h1Y865Qm";

(function(){
  const style=document.createElement('style');
  style.textContent=`
    .detail .actions{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:12px}
    .detail .actions a{display:flex!important;align-items:center;justify-content:center;box-sizing:border-box;min-width:0;min-height:44px;padding:10px 6px;border-radius:9px;font-size:13px;font-weight:800;text-decoration:none!important;white-space:nowrap}
    .detail-link{margin:0!important;background:#0b8f58;color:#fff!important}
    .detail-link:hover{filter:brightness(.95)}
    .rating-box{margin-top:20px;padding:16px;border:1px solid #e7ede9;border-radius:18px;background:#f3faf6;text-align:right}
    .rating-box-title{font-weight:800;font-size:16px;margin-bottom:8px}
    .rating-choices{display:flex;direction:ltr;gap:5px;margin:7px 0 10px}
    .rating-choice{font-size:31px;color:#c9cec9;cursor:pointer;padding:0 2px;border:0;background:transparent}
    .rating-choice.selected{color:#e2a400}
    .rating-submit{width:100%;margin-top:5px}
    .link-field{padding:12px;border:1px solid #dce7e1;border-radius:14px;background:#f7fbf9}
    .link-field label{font-weight:800}
    .detail .detail-img{cursor:zoom-in}
    .image-lightbox{position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.88);display:flex;align-items:center;justify-content:center;padding:18px;box-sizing:border-box}
    .image-lightbox img{max-width:100%;max-height:100%;width:auto!important;height:auto!important;object-fit:contain!important;border-radius:10px;box-shadow:0 8px 35px rgba(0,0,0,.35)}
    .image-lightbox .image-close{position:absolute;top:14px;right:14px;width:42px;height:42px;border:0;border-radius:50%;background:rgba(255,255,255,.92);color:#222;font-size:28px;line-height:42px;cursor:pointer}
    .category-detail-list{display:flex;flex-direction:column;gap:12px;margin-top:18px}
    .category-detail-item{width:100%;display:flex;direction:rtl;align-items:center;gap:16px;padding:12px 14px;border:0;border-radius:20px;background:#f7faf8;box-shadow:0 2px 10px rgba(20,60,45,.06);cursor:pointer;text-align:right;color:inherit}
    .category-detail-item:active{transform:scale(.99)}
    .category-detail-thumb{width:72px;height:72px;flex:0 0 72px;border-radius:14px;object-fit:cover;background:#e8f2ed}
    .category-detail-placeholder,.category-detail-design{display:flex;align-items:center;justify-content:center;font-size:34px;background:linear-gradient(145deg,#eaf8f0,#d7eee2);border:1px solid #d4e9dd;box-sizing:border-box}
    .category-detail-name{flex:1;font-size:18px;font-weight:800}
    .category-detail-arrow{font-size:30px;color:#888;line-height:1}
    .category-detail-count{display:block;margin-top:4px;font-size:12px;font-weight:500;color:#7a857f}
    .provider-form-help{display:block;margin-top:6px;font-size:12px;color:#65736c;line-height:1.6}
    .provider-form-hidden{display:none!important}
    @media(max-width:520px){.detail .actions a{font-size:11px;padding:9px 3px}.category-detail-item{gap:12px;padding:10px 12px}.category-detail-thumb{width:70px;height:70px;flex-basis:70px}.category-detail-name{font-size:16px}.category-detail-arrow{font-size:26px}.category-detail-design{font-size:32px}}
  `;
  document.head.appendChild(style);
  let currentServiceId=null;
  const fingerprint=()=>{let x=localStorage.getItem('dabbarli_rating_fp');if(!x){x=crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random();localStorage.setItem('dabbarli_rating_fp',x)}return x};
  function makeLink(url){const a=document.createElement('a');a.className='detail-link stored-detail-link';a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='🔗 رابط';return a}
  function moveExistingLink(detail){if(!detail)return;const actions=detail.querySelector('.actions');if(!actions)return;const candidates=[...detail.querySelectorAll('.stored-detail-link,[data-link-button]')];candidates.forEach(a=>{if(a.parentElement!==actions)actions.appendChild(a)});[...detail.querySelectorAll('a')].forEach(a=>{const text=(a.textContent||'').trim();if(a.parentElement!==actions&&/فتح الرابط|الرابط|🔗/.test(text))actions.appendChild(a)})}
  function addStoredLink(detail){if(!detail)return;const actions=detail.querySelector('.actions');if(!actions)return;moveExistingLink(detail);if(actions.querySelector('.stored-detail-link'))return;let service=null;try{service=window.__dabbarliServices?.find(x=>String(x.id)===String(currentServiceId))||window.__dabbarliServices?.find(x=>String(x.name||'').trim()===(detail.querySelector('h2')?.textContent||'').trim())}catch(e){}const url=String(service?.link||'').trim();if(url)actions.appendChild(makeLink(url))}
  function openImage(url){if(!url)return;const old=document.querySelector('.image-lightbox');if(old)old.remove();const box=document.createElement('div');box.className='image-lightbox';box.innerHTML='<button class="image-close" type="button" aria-label="إغلاق">×</button><img alt="صورة الخدمة">';box.querySelector('img').src=url;const close=()=>box.remove();box.querySelector('.image-close').onclick=close;box.addEventListener('click',e=>{if(e.target===box)close()});document.addEventListener('keydown',function escImage(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',escImage)}});document.body.appendChild(box)}
  function enableImageZoom(detail){const img=detail?.querySelector('.detail-img');if(!img||img.dataset.zoomEnabled)return;img.dataset.zoomEnabled='1';img.addEventListener('click',()=>openImage(img.currentSrc||img.src))}
  async function addRating(detail){if(!currentServiceId||detail.querySelector('.rating-box'))return;const box=document.createElement('div');box.className='rating-box';box.innerHTML='<div class="rating-box-title">قيّم هذه الخدمة</div><div class="rating-choices"><button type="button" class="rating-choice" data-r="1">★</button><button type="button" class="rating-choice" data-r="2">★</button><button type="button" class="rating-choice" data-r="3">★</button><button type="button" class="rating-choice" data-r="4">★</button><button type="button" class="rating-choice" data-r="5">★</button></div><button type="button" class="primary rating-submit" disabled>إرسال التقييم</button><div class="muted rating-status"></div>';const actions=detail.querySelector('.actions');detail.insertBefore(box,actions||null);const c=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let selected=0;box.querySelectorAll('.rating-choice').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.r);box.querySelectorAll('.rating-choice').forEach(x=>x.classList.toggle('selected',Number(x.dataset.r)<=selected));box.querySelector('.rating-submit').disabled=false});const status=box.querySelector('.rating-status'),submit=box.querySelector('.rating-submit');try{const {data}=await c.from('ratings').select('rating').eq('service_id',currentServiceId).eq('fingerprint',fingerprint()).limit(1);if(data?.length){status.textContent='لقد قيّمت هذه الخدمة من قبل.';box.querySelectorAll('.rating-choice').forEach(x=>x.disabled=true)}}catch(e){}try{const {data}=await c.from('ratings').select('rating').eq('service_id',currentServiceId);if(data){const avg=data.length?data.reduce((a,x)=>a+Number(x.rating||0),0)/data.length:0;const row=detail.querySelector('.rating-row');if(row)row.innerHTML='<span class="star">★</span><span>'+avg.toFixed(1)+' ('+data.length+')</span>'}}catch(e){}submit.onclick=async()=>{if(!selected)return;submit.disabled=true;status.textContent='جاري إرسال التقييم...';const {error}=await c.from('ratings').insert({service_id:currentServiceId,rating:selected,fingerprint:fingerprint()});if(error){status.textContent=error.code==='23505'?'لقد قيّمت هذه الخدمة من قبل.':'تعذر إرسال التقييم، حاول مرة أخرى.';return}status.textContent='شكرًا لك، تم تسجيل تقييمك.';box.querySelectorAll('.rating-choice').forEach(x=>x.disabled=true);const {data}=await c.from('ratings').select('rating').eq('service_id',currentServiceId);if(data){const avg=data.reduce((a,x)=>a+Number(x.rating||0),0)/data.length;const row=detail.querySelector('.rating-row');if(row)row.innerHTML='<span class="star">★</span><span>'+avg.toFixed(1)+' ('+data.length+')</span>'}}}
  function ensureLinkField(){const form=document.getElementById('addForm');if(!form||form.querySelector('[name="link"]'))return;const details=form.querySelector('[name="details"]');const field=document.createElement('div');field.className='field link-field';field.innerHTML='<label>رابط الموقع أو Google Maps</label><input name="link" type="url" placeholder="https://maps.google.com/... أو رابط الموقع">';if(details){const detailsField=details.closest('.field');if(detailsField)detailsField.parentNode.insertBefore(field,detailsField);else form.appendChild(field)}else form.appendChild(field)}
  const transportDetails=['سيارات أجرة','سيارات نقل','شاحنات نقل','شاحنات كبيرة','شاحنات الماء','شاحنات الغاز','جرارات','جرافات','حفارات','رافعات','شاحنات تبريد','نقل البضائع','نقل الأثاث','سائق خاص','سفريات','ميكانيكي','كهرباء سيارات','تصليح سيارات','تصليح شاحنات','غسيل سيارات','زيوت','إطارات','قطع غيار','بيع سيارات','كراء سيارات','دراجات نارية','إصلاح دراجات'];
  const transportDesigns={'سيارات أجرة':'🚕','سيارات نقل':'🚐','شاحنات نقل':'🚚','شاحنات كبيرة':'🚛','شاحنات الماء':'💧','شاحنات الغاز':'🔥','جرارات':'🚜','جرافات':'🏗️','حفارات':'🚧','رافعات':'🏗️','شاحنات تبريد':'❄️','نقل البضائع':'📦','نقل الأثاث':'🛋️','سائق خاص':'👨‍✈️','سفريات':'🚌','ميكانيكي':'🔧','كهرباء سيارات':'⚡','تصليح سيارات':'🛠️','تصليح شاحنات':'🔩','غسيل سيارات':'🧽','زيوت':'🛢️','إطارات':'🛞','قطع غيار':'⚙️','بيع سيارات':'🚘','كراء سيارات':'🔑','دراجات نارية':'🏍️','إصلاح دراجات':'🔩'};
  function findTransportService(name){const list=window.__dabbarliServices||[];return list.find(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name)}
  function transportDesignFor(name){return transportDesigns[name]||'🚚'}
  function showTransportSpecialty(name){const list=(window.__dabbarliServices||[]).filter(s=>String(s.specialty||'').trim()===name||String(s.name||'').trim()===name);const html=list.length?list.map(s=>card(s)).join(''):'<div class="empty">لا توجد خدمات منشورة في هذا التخصص بعد.</div>';content.innerHTML='<div class="page-card"><div class="section-head"><h2>'+esc(name)+'</h2><button class="see-all" id="transportBack">‹ النقل والمركبات</button></div><div class="services">'+html+'</div></div>';document.getElementById('transportBack')?.addEventListener('click',()=>renderTransportDetails())}
  function renderTransportDetails(){const list=window.__dabbarliServices||[];const items=transportDetails.map(name=>{const count=list.filter(x=>String(x.specialty||'').trim()===name||String(x.name||'').trim()===name).length;const thumb='<div class="category-detail-thumb category-detail-design" aria-hidden="true">'+transportDesignFor(name)+'</div>';return '<button type="button" class="category-detail-item" data-transport="'+esc(name)+'">'+thumb+'<span class="category-detail-name">'+esc(name)+(count?'<small class="category-detail-count">'+count+' خدمة</small>':'')+'</span><span class="category-detail-arrow">‹</span></button>'}).join('');content.innerHTML='<div class="page-card"><div class="section-head"><h2>النقل والمركبات</h2><button class="see-all" id="transportHome">‹ الرئيسية</button></div><div class="category-detail-list">'+items+'</div></div>';document.getElementById('transportHome')?.addEventListener('click',()=>home());content.querySelectorAll('[data-transport]').forEach(b=>b.addEventListener('click',()=>showTransportSpecialty(b.dataset.transport)))}
  window.renderTransportDetails=renderTransportDetails;window.showTransportSpecialty=showTransportSpecialty;
  function enhanceCategoryDetails(){const h=content.querySelector('.page-card .section-head h2');if(!h)return;const title=(h.textContent||'').trim().replace(/^[^\u0600-\u06FF]+/,'').trim();if((title.includes('النقل والمركبات')||title.includes('النقل والآليات'))&&!content.querySelector('.category-detail-list'))renderTransportDetails()}
  function enhance(){const detail=document.querySelector('.detail');if(detail){moveExistingLink(detail);addStoredLink(detail);enableImageZoom(detail);addRating(detail)}ensureLinkField();enhanceCategoryDetails()}
  document.addEventListener('click',e=>{const b=e.target.closest('button[onclick*="showDetail"]');if(!b)return;const m=String(b.getAttribute('onclick')||'').match(/showDetail\(['"]([^'"]+)['"]\)/);if(m)currentServiceId=m[1];setTimeout(enhance,50);setTimeout(enhance,300)},true);
  const observer=new MutationObserver(()=>{setTimeout(enhance,20);setTimeout(enhance,150)});observer.observe(document.getElementById('content')||document.body,{childList:true,subtree:true});
  const wrapTransportCategory=()=>{if(typeof window.category!=='function'){setTimeout(wrapTransportCategory,100);return}if(window.category.__dabbarliTransportWrapped)return;const original=window.category;window.category=function(type){const t=String(type||'').trim();if(t.includes('النقل والمركبات')||t.includes('النقل والآليات')){window.__dabbarliServices=services.length?services:(window.__dabbarliServices||[]);renderTransportDetails();return}return original.apply(this,arguments)};window.category.__dabbarliTransportWrapped=true};
  setTimeout(wrapTransportCategory,50);setTimeout(wrapTransportCategory,300);setTimeout(wrapTransportCategory,1000);
  setTimeout(ensureLinkField,300);
  const normalizeProviderForm=()=>{const form=document.getElementById('addForm');if(!form)return;const by=n=>form.querySelector('[name="'+n+'"]');const names=['name','category','specialty','phone','whatsapp','facebook','area','image','link','details'];const fields={};names.forEach(n=>{const el=by(n);if(el)fields[n]=el.closest('.field')||el.parentElement});if(fields.name&&fields.category&&fields.specialty){const order=['name','category','specialty','phone','whatsapp','facebook','area','image','link','details'];const anchor=fields.name;order.forEach(n=>{if(fields[n])form.insertBefore(fields[n],anchor.nextSibling);});}const nt=by('newType');if(nt){const f=nt.closest('.field')||nt.parentElement;f.classList.add('provider-form-hidden')}const labels={name:'الاسم *',category:'المجال *',specialty:'التخصص *',phone:'رقم الهاتف *',whatsapp:'رقم واتساب إذا وجد',facebook:'رابط الفيسبوك',area:'المنطقة',image:'الصورة للشركة أو الخدمة',link:'رابط الموقع أو Google Maps',details:'تفاصيل إن وجدت'};Object.keys(labels).forEach(n=>{const el=by(n);const lab=el?.closest('.field')?.querySelector('label');if(lab)lab.textContent=labels[n]});const img=by('image');if(img&&!img.closest('.field')?.querySelector('.provider-form-help')){const help=document.createElement('small');help.className='provider-form-help';help.textContent='إذا لم تكن هناك صورة، سيُنشئ دبّرلي صورة تعريفية متوافقة مع الخدمة تلقائيًا.';img.closest('.field').appendChild(help)}const link=by('link');if(link){link.type='url';link.placeholder='رابط الموقع أو Google Maps (https://maps.google.com/...)'}};
  const placeholderImage=s=>{const name=String(s?.specialty||s?.category||s?.name||'خدمة').trim();const icons={'كهربائي منازل':'⚡','سباك':'🚰','نجار':'🪚','حداد':'🔨','بناء وترميم':'🧱','دهان وطلاء':'🎨','تكييف وتبريد':'❄️','تنظيف منازل':'🧹','سيارات أجرة':'🚕','ميكانيكي':'🔧','تصليح سيارات':'🛠️','كراء سيارات':'🔑','سفريات':'🚌','شاحنات نقل':'🚚','نقل البضائع':'📦','طبيب عام':'🩺','صيدليات':'💊','طبيب بيطري':'🐄','جرارات':'🚜','هواتف':'📱','حواسيب':'💻','برمجة':'👨‍💻','دروس خصوصية':'📚','حلاقة رجالية':'💈','تجميل نسائي':'💄','خدمات توصيل':'📦','شبكات وإنترنت':'📡','إلكترونيات':'📱','أجهزة كهرومنزلية':'🔌'};const icon=icons[name]||'🛠️';const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="700" viewBox="0 0 1200 700"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#eaf8f0"/><stop offset="1" stop-color="#cfe9dc"/></linearGradient></defs><rect width="1200" height="700" rx="36" fill="url(#g)"/><circle cx="600" cy="240" r="120" fill="#fff" opacity=".82"/><text x="600" y="285" text-anchor="middle" font-size="145">${icon}</text><text x="600" y="455" text-anchor="middle" font-family="Arial,sans-serif" font-size="42" font-weight="700" fill="#147a50">${name.replace(/[&<>]/g,'')}</text><text x="600" y="515" text-anchor="middle" font-family="Arial,sans-serif" font-size="24" fill="#557268">صورة تعريفية مولّدة من دبّرلي</text></svg>';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)};
  const enrichPublicProviders=()=>{const list=window.__dabbarliPublicServices;if(!Array.isArray(list))return;const phones={'public-yassir':'0782090000','public-yalidine':'0982308080','public-zr':'0230000000','public-numilog':'0770963463','public-airalgerie':'021986363','public-sntf':'021711510','public-aramex':'0982312412','public-mobilis':'0655002999','public-at':'12','public-iris':'036448559','public-naftal':'3305'};list.forEach(s=>{if(!s.phone&&phones[s.id])s.phone=phones[s.id];if(!s.whatsapp&&s.phone&&String(s.phone).replace(/\D/g,'').length>=9)s.whatsapp=s.phone;if(!s.img)s.img=placeholderImage(s)});window.__dabbarliPublicServices=list};
  const wrapLoadServices=()=>{if(typeof window.loadServices!=='function'){setTimeout(wrapLoadServices,100);return}if(window.loadServices.__dabbarliWrapped)return;const original=window.loadServices;window.loadServices=async function(){await original.apply(this,arguments);try{enrichPublicProviders();const pub=Array.isArray(window.__dabbarliPublicServices)?window.__dabbarliPublicServices:[];services.forEach(s=>{const p=pub.find(x=>String(x.id)===String(s.id));if(p){s.phone=p.phone||s.phone;s.whatsapp=p.whatsapp||s.whatsapp;s.facebook=p.facebook||s.facebook;s.link=p.link||s.link;s.img=s.image_url||p.img||placeholderImage(s)}else if(!s.image_url)s.img=placeholderImage(s)});window.__dabbarliServices=services}catch(e){}};window.loadServices.__dabbarliWrapped=true};
  setInterval(normalizeProviderForm,500);
  setInterval(enrichPublicProviders,1000);
  setTimeout(wrapLoadServices,50);
  const categoryScript=document.createElement('script');categoryScript.src='category-details.js?v=20260912-35';document.head.appendChild(categoryScript);
})();